import { useEffect, useState } from 'react'
import { Info } from 'lucide-react'
import readmeManifest from '../../lib/data/readme-manifest'
import { useLocale, useT } from '../../lib/i18n'
import type { Locale } from '../../lib/i18n'
import type { AppCard } from '../../lib/types/app'
import ExternalLink from './external-link'
import ReachOutLeadingIcon from '../reach-out-icons'

type ReadmeDocument = {
  sourceLocale: Locale
  html: string
}

/**
 * Renders the project's own README, fetched from public/readme/ — generated by
 * `bun run readmes`, so the markup is sanitized at build time rather than here.
 */
function ReadmeSection({ app }: { app: AppCard }) {
  const t = useT()
  const { locale } = useLocale()
  const translations = readmeManifest[app.id]
  const [document, setDocument] = useState<ReadmeDocument | null>(null)
  const [failed, setFailed] = useState(false)

  useEffect(() => {
    if (!translations) {
      return
    }

    let cancelled = false
    setDocument(null)
    setFailed(false)

    fetch(`${import.meta.env.BASE_URL}readme/${app.id}.${locale}.json`)
      .then((response) => (response.ok ? response.json() : Promise.reject(response.status)))
      .then((data: ReadmeDocument) => {
        if (!cancelled) {
          setDocument(data)
        }
      })
      .catch(() => {
        if (!cancelled) {
          setFailed(true)
        }
      })

    return () => {
      cancelled = true
    }
  }, [app.id, locale, translations])

  if (!translations) {
    return null
  }

  return (
    <section className='project-section project-readme-section'>
      <div className='project-readme-head'>
        <h2>{t.apps.documentation}</h2>
        {app.repo ? (
          <ExternalLink className='project-readme-source' href={app.repo}>
            <ReachOutLeadingIcon name='github' size={14} />
            <span>{t.apps.viewOnGitHub}</span>
          </ExternalLink>
        ) : null}
      </div>

      {failed ? <p className='project-readme-note'>{t.apps.readmeError}</p> : null}

      {document ? (
        <>
          {document.sourceLocale !== locale ? (
            <p className='project-readme-note'>
              <Info size={14} aria-hidden='true' />
              <span>{t.apps.readmeFallback}</span>
            </p>
          ) : null}
          <div className='project-readme' dangerouslySetInnerHTML={{ __html: document.html }} />
        </>
      ) : null}
    </section>
  )
}

export default ReadmeSection
