/**
 * Pulls the two things on this site that go stale on their own: a repo's star
 * and fork counts, and the article list.
 *
 * Run deliberately (`bun run sync`), not from `bun run build` — the output is
 * committed, exactly like `bun run readmes`, so CI builds stay offline and a
 * GitHub or Substack outage cannot fail a deploy. The cost is that a refresh is
 * a command plus a commit; the gain is that the site has no runtime dependency
 * on anyone's API and no unauthenticated rate limit to hit in a visitor's
 * browser.
 *
 * Both outputs are generated files with a header saying so. `apps.ts` stays
 * hand-written: it holds the decisions (which projects, in what order, with
 * what accent), and this script never touches it.
 */

import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import apps from '../src/lib/data/apps'
import type { AppId } from '../src/lib/types/app'
import type { Article } from '../src/lib/types/article'

const ROOT = resolve(import.meta.dirname, '..')
const STATS_OUT = resolve(ROOT, 'src/lib/data/repo-stats.ts')
const ARTICLES_OUT = resolve(ROOT, 'src/lib/data/articles.ts')

const PUBLICATION = 'https://penoloxai.substack.com'
const FEED = `${PUBLICATION}/feed`
const ARCHIVE = `${PUBLICATION}/api/v1/archive?sort=new&limit=50`

/**
 * Substack answers 403 to GitHub Actions runners — the same request succeeds
 * from a laptop and from other datacenters, so the block is on that IP range,
 * not on the client. A browser User-Agent is tried as well, and the JSON
 * archive endpoint is a separate route that may be filtered differently.
 */
const BROWSER_UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36'

type Stats = { stars: number; forks: number }

async function gh<T>(path: string): Promise<T | null> {
  const headers: Record<string, string> = { Accept: 'application/vnd.github+json' }
  if (process.env.GITHUB_TOKEN) {
    headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`
  }

  const response = await fetch(`https://api.github.com${path}`, { headers })
  if (!response.ok) {
    return null
  }

  return (await response.json()) as T
}

function parseRepo(url: string): { owner: string; name: string } | null {
  const match = /^https:\/\/github\.com\/([^/]+)\/([^/]+)/.exec(url)
  return match ? { owner: match[1], name: match[2] } : null
}

async function syncStats(): Promise<number> {
  const stats: Partial<Record<AppId, Stats>> = {}

  for (const app of apps) {
    if (!app.repo) continue
    const parsed = parseRepo(app.repo)
    if (!parsed) continue

    const info = await gh<{ stargazers_count: number; forks_count: number }>(
      `/repos/${parsed.owner}/${parsed.name}`
    )
    if (!info) {
      // A private or renamed repo is not an error worth failing the run over —
      // the card simply shows no counts, which is what it did before any of
      // this existed.
      console.warn(`! ${app.id}: repo not reachable, counts left out`)
      continue
    }

    stats[app.id] = { stars: info.stargazers_count, forks: info.forks_count }
    console.log(`✓ ${app.id}  ★ ${info.stargazers_count}  ⑂ ${info.forks_count}`)
  }

  await writeFile(
    STATS_OUT,
    `import type { AppId } from '../types/app'\n\n` +
      `/**\n * Generated by \`bun run sync\` — do not edit by hand.\n *\n` +
      ` * Only repos GitHub answered for are listed. A project with no entry\n` +
      ` * renders without counts, which is also what a project with no repo does.\n */\n` +
      `export const repoStats: Partial<Record<AppId, { stars: number; forks: number }>> = ` +
      `${JSON.stringify(stats, null, 2)}\n\nexport default repoStats\n`
  )

  return Object.keys(stats).length
}

/** The feed is small and well-formed; a parser dependency would outweigh it. */
function tag(item: string, name: string): string {
  const match = new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`).exec(item)
  if (!match) return ''
  return match[1]
    .replace(/^\s*<!\[CDATA\[([\s\S]*?)\]\]>\s*$/, '$1')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&')
    .trim()
}

/** Articles from the RSS feed, or null with the reason logged */
async function fromFeed(userAgent?: string): Promise<Article[] | null> {
  const label = userAgent ? 'feed (browser UA)' : 'feed'
  const response = await fetch(FEED, userAgent ? { headers: { 'User-Agent': userAgent } } : {})
  if (!response.ok) {
    console.warn(`! ${label} returned ${response.status}`)
    return null
  }

  const xml = await response.text()
  const items = [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].map((m) => m[1])

  const articles: Article[] = []
  for (const item of items) {
    const href = tag(item, 'link')
    const title = tag(item, 'title')
    if (!href || !title) continue

    const enclosure = /<enclosure[^>]*url="([^"]+)"/.exec(item)
    const published = tag(item, 'pubDate')

    articles.push({
      // The slug is stable across edits; the numeric post id in a share URL is
      // not the one the canonical link uses.
      id: href.split('/').pop() || href,
      href,
      title,
      subtitle: tag(item, 'description'),
      date: published ? new Date(published).toISOString().slice(0, 10) : '',
      source: 'Substack',
      ...(enclosure ? { imageUrl: enclosure[1] } : {}),
    })
  }

  return articles
}

type ArchivePost = {
  slug: string
  canonical_url: string
  title: string
  subtitle: string | null
  post_date: string
  cover_image: string | null
}

/** Articles from the JSON archive endpoint, or null with the reason logged */
async function fromArchive(): Promise<Article[] | null> {
  const response = await fetch(ARCHIVE, {
    headers: { 'User-Agent': BROWSER_UA, Accept: 'application/json' },
  })
  if (!response.ok) {
    console.warn(`! archive API returned ${response.status}`)
    return null
  }

  const posts = (await response.json()) as ArchivePost[]
  return posts
    .filter((post) => post.canonical_url && post.title)
    .map((post) => ({
      id: post.slug,
      href: post.canonical_url,
      title: post.title,
      subtitle: post.subtitle ?? '',
      date: post.post_date.slice(0, 10),
      source: 'Substack',
      ...(post.cover_image ? { imageUrl: post.cover_image } : {}),
    }))
}

async function syncArticles(): Promise<number> {
  const sources: [string, () => Promise<Article[] | null>][] = [
    ['feed', () => fromFeed()],
    ['feed (browser UA)', () => fromFeed(BROWSER_UA)],
    ['archive API', fromArchive],
  ]

  for (const [label, load] of sources) {
    let articles: Article[] | null
    try {
      articles = await load()
    } catch (error) {
      console.warn(`! ${label} failed: ${(error as Error).message}`)
      continue
    }

    // An empty list from a source that answered is suspicious, not news —
    // wiping the section on a hiccup is worse than leaving it as it was
    if (!articles?.length) continue

    // Newest first, which is the order the section renders in.
    articles.sort((a, b) => b.date.localeCompare(a.date))

    await writeFile(
      ARTICLES_OUT,
      `import type { Article } from '../types/article'\n\n` +
        `/**\n * Generated by \`bun run sync\` from ${PUBLICATION} — do not edit by hand.\n */\n` +
        `const articles: Article[] = ${JSON.stringify(articles, null, 2)}\n\n` +
        `export default articles\n`
    )

    console.log(`✓ articles from ${label}`)
    return articles.length
  }

  console.warn('! every article source failed, articles left as they were')
  return -1
}

const counted = await syncStats()
const articles = await syncArticles()

console.log(`\nrepo stats → src/lib/data/repo-stats.ts (${counted} repos)`)
console.log(
  articles < 0
    ? 'articles → unchanged'
    : `articles → src/lib/data/articles.ts (${articles})`
)
