import type { Article } from '../types/article'

/**
 * Generated by `bun run sync` from https://penoloxai.substack.com/feed — do not edit by hand.
 */
const articles: Article[] = [
  {
    "id": "anthropic-deleted-80-of-claude-codes",
    "href": "https://penoloxai.substack.com/p/anthropic-deleted-80-of-claude-codes",
    "title": "Anthropic deleted 80% of Claude Code's system prompt",
    "subtitle": "Nothing measurable broke. Here is what that means for the CLAUDE.md, skills, and prompts you have quietly been collecting.",
    "date": "2026-08-09",
    "source": "Substack",
    "imageUrl": "https://substackcdn.com/image/fetch/$s_!_VVJ!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F4e616e68-2715-4937-83a1-577a55341880_1435x1092.png"
  }
]

export default articles
