import type { Locale } from '../i18n/types'
import type { AppId } from '../types/app'

/**
 * Generated by `bun run readmes` — do not edit by hand.
 *
 * Keys are the projects with a rendered README under public/readme/. The value
 * lists the locales that have their own translation; every other locale falls
 * back to English and the page says so.
 */
export const readmeManifest: Partial<Record<AppId, Locale[]>> = {
  "portkill": [
    "en"
  ],
  "macshelf": [
    "en"
  ],
  "portfolio": [
    "en"
  ]
}

export default readmeManifest
