import type { AppId } from '../types/app'

/**
 * Generated by `bun run sync` — do not edit by hand.
 *
 * Only repos GitHub answered for are listed. A project with no entry
 * renders without counts, which is also what a project with no repo does.
 */
export const repoStats: Partial<Record<AppId, { stars: number; forks: number }>> = {
  "portkill": {
    "stars": 2,
    "forks": 0
  },
  "macshelf": {
    "stars": 2,
    "forks": 0
  },
  "skadi": {
    "stars": 1,
    "forks": 0
  },
  "penote": {
    "stars": 30,
    "forks": 2
  },
  "portfolio": {
    "stars": 2,
    "forks": 0
  }
}

export default repoStats
